### ISSUE TITLE
.pyi stubfile for code completion

### ISSUE THREAD

**Issue by pixel-ninja** [Correct-Syntax/py-oiio#3]
Thanks for the guide!

I just wanted to add that in my case it was useful to generate a .pyi stub file so that code completion would work properly.

With mypy installed running the following from the oiio folder will produce the pyi file:
`stubgen -m OpenImageIO -o ./`

**Comment by Correct-Syntax** [comment]
Thanks for the tip. 🎉  I've updated the steps to include this.
